name: reclaim
description: Reclaim
version: 0.0.1+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"
  flutter: ">=3.38.0 <4.0.0"

dependencies:
  async: ^2.12.0
  bloc: ^9.0.0
  bloc_effects: ^2.0.1
  cupertino_icons: ^1.0.8
  device_info_plus: ^12.0.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.1.0
  freezed_annotation: ^3.0.0
  get_it: ^9.2.1
  go_router: ^17.1.0
  google_fonts: ^8.1.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  lottie: ^3.1.2
  meta: ^1.16.0
  pretty_dio_logger: ^1.4.0
  retrofit: ^4.9.2
  rxdart: ^0.28.0
  shared_preferences: ^2.3.2
  typewritertext: ^3.0.9

dev_dependencies:
  analyzer: ^8.4.1
  bloc_test: ^10.0.0
  build_runner: ^2.12.2
  build_verify: ^3.1.0
  flutter_gen_runner: ^5.5.0+1
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  mocktail: ^1.0.3
  retrofit_generator: ^10.2.0
  very_good_analysis: ^10.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/

#  fonts:
#    - family: Averta
#      fonts:
#        - asset: assets/fonts/averta/AvertaStd-Regular.otf
#        - asset: assets/fonts/averta/AvertaStd-Regular.otf
#          weight: 400
#        - asset: assets/fonts/averta/AvertaStd-RegularItalic.otf
#          weight: 400
#          style: italic
#        - asset: assets/fonts/averta/AvertaStd-Semibold.otf
#          weight: 600
#        - asset: assets/fonts/averta/AvertaStd-SemiboldItalic.otf
#          weight: 600
#          style: italic
#        - asset: assets/fonts/averta/AvertaStd-Bold.otf
#          weight: 700
#        - asset: assets/fonts/averta/AvertaStd-BoldItalic.otf
#          weight: 700
#          style: italic
#        - asset: assets/fonts/averta/AvertaStd-Extrabold.otf
#          weight: 800
#        - asset: assets/fonts/averta/AvertaStd-ExtraboldItalic.otf
#          weight: 800
#          style: italic
#        - asset: assets/fonts/averta/AvertaStd-Black.otf
#          weight: 900
#        - asset: assets/fonts/averta/AvertaStd-BlackItalic.otf
#          weight: 900
#          style: italic

flutter_gen:
  output: lib/assets_gen/
  line_length: 1000
  integrations:
    flutter_svg: false
    rive: false
    lottie: false
